title: Yeet Mac Banner Notifications into the Void from Bash
description: When Banners Pop Up, Keep Your Hands on Your Keyboard and Use the Terminal to Keep Going
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
