title: Yeet Mac Banner Notifications into the Void from Bash
description: Use the Terminal to Keep Your Hands on Your Keyboard and Keep Going
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
